### ISSUE TITLE
Will PR be accepted for changes and fixes? 

### ISSUE THREAD

**Issue by seivan** [watchexec/cargo-watch#329]
I find cargo-watch to be better and more stable than Bacon, especially for UI applications.
I was wondering if you'd accept a PR adding configuration inside `cargo.toml`.
Any filters and flags could be under a specific name 

```toml
[package.metadata.watch]
#all flags default regardless of task 


[package.metadata.watch.tasks.simple]
command = ["run" "--example", "simple"]
#override flags 
#options 
```

So you'd be able to do `cargo watch simple`
